//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebInvenotry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryMgntEntities : DbContext
    {
        public InventoryMgntEntities()
            : base("name=InventoryMgntEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ReferralCode1> ReferralCode1 { get; set; }
        public virtual DbSet<tbl_BankAccount> tbl_BankAccount { get; set; }
        public virtual DbSet<tbl_BankAdjustment> tbl_BankAdjustment { get; set; }
        public virtual DbSet<tbl_BanktoBankTransfer> tbl_BanktoBankTransfer { get; set; }
        public virtual DbSet<tbl_CashAdjustment> tbl_CashAdjustment { get; set; }
        public virtual DbSet<tbl_CashInhand> tbl_CashInhand { get; set; }
        public virtual DbSet<tbl_CategoryMaster> tbl_CategoryMaster { get; set; }
        public virtual DbSet<tbl_CompanyMaster> tbl_CompanyMaster { get; set; }
        public virtual DbSet<tbl_CreditNote1> tbl_CreditNote1 { get; set; }
        public virtual DbSet<tbl_CreditNoteInner> tbl_CreditNoteInner { get; set; }
        public virtual DbSet<tbl_DebitNote> tbl_DebitNote { get; set; }
        public virtual DbSet<tbl_DebitNoteInner> tbl_DebitNoteInner { get; set; }
        public virtual DbSet<tbl_DeliveryChallan> tbl_DeliveryChallan { get; set; }
        public virtual DbSet<tbl_DeliveryChallanInner> tbl_DeliveryChallanInner { get; set; }
        public virtual DbSet<tbl_ExpenseCategory> tbl_ExpenseCategory { get; set; }
        public virtual DbSet<tbl_Expenses> tbl_Expenses { get; set; }
        public virtual DbSet<tbl_ExpensesInner> tbl_ExpensesInner { get; set; }
        public virtual DbSet<tbl_ItemAdjustement> tbl_ItemAdjustement { get; set; }
        public virtual DbSet<tbl_ItemMaster> tbl_ItemMaster { get; set; }
        public virtual DbSet<tbl_ItemServicemaster> tbl_ItemServicemaster { get; set; }
        public virtual DbSet<tbl_LoanBank> tbl_LoanBank { get; set; }
        public virtual DbSet<tbl_LoginPasssword> tbl_LoginPasssword { get; set; }
        public virtual DbSet<tbl_MakePayment> tbl_MakePayment { get; set; }
        public virtual DbSet<tbl_OtherIncome> tbl_OtherIncome { get; set; }
        public virtual DbSet<tbl_otherIncomeCaategory> tbl_otherIncomeCaategory { get; set; }
        public virtual DbSet<tbl_OtherIncomeInner> tbl_OtherIncomeInner { get; set; }
        public virtual DbSet<tbl_PartyGroup> tbl_PartyGroup { get; set; }
        public virtual DbSet<tbl_PartyMaster> tbl_PartyMaster { get; set; }
        public virtual DbSet<tbl_PaymentIn> tbl_PaymentIn { get; set; }
        public virtual DbSet<tbl_PaymentLink> tbl_PaymentLink { get; set; }
        public virtual DbSet<tbl_Paymentout> tbl_Paymentout { get; set; }
        public virtual DbSet<tbl_PurchaseBill> tbl_PurchaseBill { get; set; }
        public virtual DbSet<tbl_PurchaseBillInner> tbl_PurchaseBillInner { get; set; }
        public virtual DbSet<tbl_PurchaseOrder> tbl_PurchaseOrder { get; set; }
        public virtual DbSet<tbl_PurchaseOrderInner> tbl_PurchaseOrderInner { get; set; }
        public virtual DbSet<tbl_QuotationInner> tbl_QuotationInner { get; set; }
        public virtual DbSet<tbl_SaleInvoice> tbl_SaleInvoice { get; set; }
        public virtual DbSet<tbl_SaleInvoiceInner> tbl_SaleInvoiceInner { get; set; }
        public virtual DbSet<tbl_SaleOrder> tbl_SaleOrder { get; set; }
        public virtual DbSet<tbl_SaleOrderInner> tbl_SaleOrderInner { get; set; }
        public virtual DbSet<tbl_TransactionPasssword> tbl_TransactionPasssword { get; set; }
        public virtual DbSet<tbl_TransactionPrefix> tbl_TransactionPrefix { get; set; }
        public virtual DbSet<tbl_UnitConversion> tbl_UnitConversion { get; set; }
        public virtual DbSet<tbl_UnitMaster> tbl_UnitMaster { get; set; }
        public virtual DbSet<tble_NewCompany> tble_NewCompany { get; set; }
        public virtual DbSet<tblQuotation> tblQuotations { get; set; }
    }
}
