//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebInvenotry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentIn
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public Nullable<double> ReceivedAmount { get; set; }
        public Nullable<double> UnusedAmount { get; set; }
        public byte[] image { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<int> PartiesID { get; set; }
        public string TableName { get; set; }
    
        public virtual tbl_PartyMaster tbl_PartyMaster { get; set; }
    }
}
