//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebInvenotry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Expenses
    {
        public int ID { get; set; }
        public string ExpenseCategory { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<double> Total { get; set; }
        public string AdditinalFeild1 { get; set; }
        public string AdditionalFeild2 { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual tbl_ExpenseCategory tbl_ExpenseCategory { get; set; }
        public virtual tbl_Expenses tbl_Expenses1 { get; set; }
        public virtual tbl_Expenses tbl_Expenses2 { get; set; }
    }
}
