//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebInvenotry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BankAccount()
        {
            this.tbl_BanktoBankTransfer = new HashSet<tbl_BanktoBankTransfer>();
        }
    
        public int ID { get; set; }
        public string AccountName { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public Nullable<double> OpeningBal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string additionalFeild { get; set; }
        public string additinalFeild2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BanktoBankTransfer> tbl_BanktoBankTransfer { get; set; }
    }
}
