//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebInvenotry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PartyGroup
    {
        public int PartyGroupID { get; set; }
        public string AddPartyGroup { get; set; }
        public string AdditionalFeild1 { get; set; }
        public Nullable<System.DateTime> AdditionalFeild2 { get; set; }
    }
}
