//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebInvenotry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OtherIncome
    {
        public int ID { get; set; }
        public string IncomeCategory { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string paymentType { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<double> RoundOFF { get; set; }
        public Nullable<double> total { get; set; }
        public string AdditionalFeild1 { get; set; }
        public string Additional2 { get; set; }
        public string Additional3 { get; set; }
        public string Additional4 { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> Balance { get; set; }
    
        public virtual tbl_otherIncomeCaategory tbl_otherIncomeCaategory { get; set; }
        public virtual tbl_otherIncomeCaategory tbl_otherIncomeCaategory1 { get; set; }
        public virtual tbl_otherIncomeCaategory tbl_otherIncomeCaategory2 { get; set; }
    }
}
