//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebInvenotry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CategoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CategoryMaster()
        {
            this.tbl_ItemMaster = new HashSet<tbl_ItemMaster>();
            this.tbl_ItemMaster1 = new HashSet<tbl_ItemMaster>();
            this.tbl_ItemMaster2 = new HashSet<tbl_ItemMaster>();
            this.tbl_PurchaseBillInner = new HashSet<tbl_PurchaseBillInner>();
            this.tbl_PurchaseOrderInner = new HashSet<tbl_PurchaseOrderInner>();
            this.tbl_QuotationInner = new HashSet<tbl_QuotationInner>();
            this.tbl_SaleInvoiceInner = new HashSet<tbl_SaleInvoiceInner>();
            this.tbl_SaleOrderInner = new HashSet<tbl_SaleOrderInner>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string AdditionalFeild { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemMaster> tbl_ItemMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemMaster> tbl_ItemMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemMaster> tbl_ItemMaster2 { get; set; }
        public virtual tbl_CategoryMaster tbl_CategoryMaster1 { get; set; }
        public virtual tbl_CategoryMaster tbl_CategoryMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseBillInner> tbl_PurchaseBillInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseOrderInner> tbl_PurchaseOrderInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuotationInner> tbl_QuotationInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleInvoiceInner> tbl_SaleInvoiceInner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleOrderInner> tbl_SaleOrderInner { get; set; }
    }
}
