//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwebInvenotry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PartyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PartyMaster()
        {
            this.tbl_PaymentIn = new HashSet<tbl_PaymentIn>();
            this.tbl_Paymentout = new HashSet<tbl_Paymentout>();
            this.tbl_PurchaseBill = new HashSet<tbl_PurchaseBill>();
        }
    
        public int PartiesID { get; set; }
        public string PartyName { get; set; }
        public string ContactNo { get; set; }
        public string BillingAddress { get; set; }
        public string EmailID { get; set; }
        public string GSTType { get; set; }
        public string State { get; set; }
        public Nullable<double> OpeningBal { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public string AddRemainder { get; set; }
        public string PartyType { get; set; }
        public string ShippingAddress { get; set; }
        public string AdditionalFeild1 { get; set; }
        public string AdditionalFeild2 { get; set; }
        public string AdditionalFeild3 { get; set; }
        public string AdditionalFeild4 { get; set; }
        public string AdditionalFeild5 { get; set; }
        public Nullable<System.DateTime> AdditionalFeild6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PaymentIn> tbl_PaymentIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Paymentout> tbl_Paymentout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseBill> tbl_PurchaseBill { get; set; }
    }
}
